<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PeaRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'subject_id' => 'required|exists:subjects,id',
            'details' => 'required|array',
            'details.career' => 'required|string',
            'details.logo_path' => 'nullable|string',
            'details.subject' => 'required|string',
            'details.subject_code' => 'required|string',
            'details.level' => 'required|string',
            'details.curricular_org_unit' => 'required|string',
            'details.academic_period' => 'required|string',
            'details.modality' => 'required|string',
            'details.teacher' => 'required|string',
            'details.email' => 'required|email',
            'details.credits' => 'required|numeric',
            'details.totalHours' => 'required|numeric',
            'details.contact_teacher' => 'required|numeric',
            'details.practical_teaching' => 'required|numeric',
            'details.self_employment' => 'required|numeric',
            'details.practical_self_employment' => 'required|numeric',
            'details.prerequisites' => 'required|array',
            'details.prerequisites_code' => 'required|array',
            'details.corequisites' => 'required|array',
            'details.corequisites_code' => 'required|array',
            'details.description_subject' => 'required|string',
            'details.objectives_subject' => 'required|string',
            'details.gral_learning_outcome' => 'required|string',
            'details.competence_specif_learningoutcomes' => 'required|array',
            'details.competence_specif_contribution_level' => 'required|array',
            'details.generic_competences' => 'required|string',
            'details.research_lines_career' => 'required|string',
            'details.description_integrative_project' => 'required|string',
            'details.teachinglearningstrategies' => 'required|string',
            'details.curricularunit_unit' => 'required|array',
            'details.curricularunit_name' => 'required|array',
            'details.curricularunit_learning_outcomes' => 'required|array',
            'details.teachingcontent_schedule' => 'required|array',
            'details.teachingcontent_content' => 'required|array',
            'details.teachingcontent_contact_teacher' => 'required|array',
            'details.teachingcontent_contact_teacher_duration' => 'required|array',
            'details.teachingcontent_practical_teaching' => 'required|array',
            'details.teachingcontent_practical_teaching_duration' => 'required|array',
            'details.teachingcontent_self_employment' => 'required|array',
            'details.teachingcontent_self_employment_duration' => 'required|array',
            'details.teachingcontent_practical_self_employment' => 'required|array',
            'details.teachingcontent_practical_self_employment_duration' => 'required|array',
            'details.totalContactTeacherHours' => 'required|numeric',
            'details.totalPracticalTeacherHours' => 'required|numeric',
            'details.totalSelfEmploymentHours' => 'required|numeric',
            'details.totalPracticalSelfEmploymentHours' => 'required|numeric',
            'details.totalHours2' => 'required|numeric',
            'details.evaluation_unit' => 'required|array',
            'details.evaluation_Learning_outcomes' => 'required|array',
            'details.evaluation_type' => 'required|array',
            'details.evaluation_criteria' => 'required|array',
            'details.evaluation_activity' => 'required|array',
            'details.evaluation_first_partial' => 'required|array',
            'details.evaluation_second_partial' => 'required|array',
            'details.totalPartial1' => 'required|numeric',
            'details.totalPartial2' => 'required|numeric',
            'details.bibliography_type' => 'required|array',
            'details.bibliography_author' => 'required|array',
            'details.bibliography_year' => 'required|array',
            'details.bibliography_title' => 'required|array',
            'details.bibliography_editorial' => 'required|array',
            'details.bibliography_format' => 'required|array',
            'details.bibliography_code' => 'required|array',
            'details.bibliography_link' => 'required|array',
            'details.bibliography_uplift' => 'required|array',
            'details.teacher_approval' => 'required|string',
            'details.coordinator_approval' => 'required|string',
            'details.vice_rector_approval' => 'required|string',
        ];
    }

    public function messages(): array
    {
        return [
            'subject_id.required' => 'El ID de la asignatura es obligatorio.',
            'subject_id.exists' => 'La asignatura seleccionada no existe.',
            'details.required' => 'Los detalles de la asignatura son obligatorios.',
            'details.array' => 'Los detalles deben ser un array.',
            'details.career.required' => 'La carrera es obligatoria.',
            'details.logo_path.required' => 'El logo es obligatoria.',
            'details.subject.required' => 'El nombre de la asignatura es obligatorio.',
            'details.subject_code.required' => 'El código de la asignatura es obligatorio.',
            'details.level.required' => 'El nivel es obligatorio.',
            'details.curricular_org_unit.required' => 'La unidad organizativa curricular es obligatoria.',
            'details.academic_period.required' => 'El período académico es obligatorio.',
            'details.modality.required' => 'La modalidad es obligatoria.',
            'details.teacher.required' => 'El profesor es obligatorio.',
            'details.email.required' => 'El email es obligatorio.',
            'details.email.email' => 'El email debe ser una dirección de correo válida.',
            'details.credits.required' => 'Los créditos son obligatorios.',
            'details.credits.numeric' => 'Los créditos deben ser un número.',
            'details.totalHours.required' => 'Las horas totales son obligatorias.',
            'details.totalHours.numeric' => 'Las horas totales deben ser un número.',
            'details.contact_teacher.required' => 'Las horas de contacto con el profesor son obligatorias.',
            'details.contact_teacher.numeric' => 'Las horas de contacto con el profesor deben ser un número.',
            'details.practical_teaching.required' => 'Las horas de enseñanza práctica son obligatorias.',
            'details.practical_teaching.numeric' => 'Las horas de enseñanza práctica deben ser un número.',
            'details.self_employment.required' => 'Las horas de autoempleo son obligatorias.',
            'details.self_employment.numeric' => 'Las horas de autoempleo deben ser un número.',
            'details.practical_self_employment.required' => 'Las horas de autoempleo práctico son obligatorias.',
            'details.practical_self_employment.numeric' => 'Las horas de autoempleo práctico deben ser un número.',
            'details.prerequisites.required' => 'Los prerrequisitos son obligatorios.',
            'details.prerequisites.array' => 'Los prerrequisitos deben ser un array.',
            'details.prerequisites_code.required' => 'Los códigos de prerrequisitos son obligatorios.',
            'details.prerequisites_code.array' => 'Los códigos de prerrequisitos deben ser un array.',
            'details.corequisites.required' => 'Los correquisitos son obligatorios.',
            'details.corequisites.array' => 'Los correquisitos deben ser un array.',
            'details.corequisites_code.required' => 'Los códigos de correquisitos son obligatorios.',
            'details.corequisites_code.array' => 'Los códigos de correquisitos deben ser un array.',
            'details.description_subject.required' => 'La descripción de la asignatura es obligatoria.',
            'details.objectives_subject.required' => 'Los objetivos de la asignatura son obligatorios.',
            'details.gral_learning_outcome.required' => 'El resultado general de aprendizaje es obligatorio.',
            'details.competence_specif_learningoutcomes.required' => 'Los resultados específicos de aprendizaje de la competencia son obligatorios.',
            'details.competence_specif_learningoutcomes.array' => 'Los resultados específicos de aprendizaje de la competencia deben ser un array.',
            'details.competence_specif_contribution_level.required' => 'El nivel de contribución específico de la competencia es obligatorio.',
            'details.competence_specif_contribution_level.array' => 'El nivel de contribución específico de la competencia debe ser un array.',
            'details.generic_competences.required' => 'Las competencias genéricas son obligatorias.',
            'details.research_lines_career.required' => 'Las líneas de investigación de la carrera son obligatorias.',
            'details.description_integrative_project.required' => 'La descripción del proyecto integrador es obligatoria.',
            'details.teachinglearningstrategies.required' => 'Las estrategias de enseñanza-aprendizaje son obligatorias.',
            'details.curricularunit_unit.required' => 'Las unidades curriculares son obligatorias.',
            'details.curricularunit_unit.array' => 'Las unidades curriculares deben ser un array.',
            'details.curricularunit_name.required' => 'Los nombres de las unidades curriculares son obligatorios.',
            'details.curricularunit_name.array' => 'Los nombres de las unidades curriculares deben ser un array.',
            'details.curricularunit_learning_outcomes.required' => 'Los resultados de aprendizaje de las unidades curriculares son obligatorios.',
            'details.curricularunit_learning_outcomes.array' => 'Los resultados de aprendizaje de las unidades curriculares deben ser un array.',
            'details.teachingcontent_schedule.required' => 'Los horarios del contenido de enseñanza son obligatorios.',
            'details.teachingcontent_schedule.array' => 'Los horarios del contenido de enseñanza deben ser un array.',
            'details.teachingcontent_content.required' => 'El contenido de enseñanza es obligatorio.',
            'details.teachingcontent_content.array' => 'El contenido de enseñanza debe ser un array.',
            'details.teachingcontent_contact_teacher.required' => 'Las horas de contacto con el profesor del contenido de enseñanza son obligatorias.',
            'details.teachingcontent_contact_teacher.array' => 'Las horas de contacto con el profesor del contenido de enseñanza deben ser un array.',
            'details.teachingcontent_contact_teacher_duration.required' => 'Las duraciones de contacto con el profesor del contenido de enseñanza son obligatorias.',
            'details.teachingcontent_contact_teacher_duration.array' => 'Las duraciones de contacto con el profesor del contenido de enseñanza deben ser un array.',
            'details.teachingcontent_practical_teaching.required' => 'Las horas de enseñanza práctica del contenido de enseñanza son obligatorias.',
            'details.teachingcontent_practical_teaching.array' => 'Las horas de enseñanza práctica del contenido de enseñanza deben ser un array.',
            'details.teachingcontent_practical_teaching_duration.required' => 'Las duraciones de enseñanza práctica del contenido de enseñanza son obligatorias.',
            'details.teachingcontent_practical_teaching_duration.array' => 'Las duraciones de enseñanza práctica del contenido de enseñanza deben ser un array.',
            'details.teachingcontent_self_employment.required' => 'Las horas de autoempleo del contenido de enseñanza son obligatorias.',
            'details.teachingcontent_self_employment.array' => 'Las horas de autoempleo del contenido de enseñanza deben ser un array.',
            'details.teachingcontent_self_employment_duration.required' => 'Las duraciones de autoempleo del contenido de enseñanza son obligatorias.',
            'details.teachingcontent_self_employment_duration.array' => 'Las duraciones de autoempleo del contenido de enseñanza deben ser un array.',
            'details.teachingcontent_practical_self_employment.required' => 'Las horas de autoempleo práctico del contenido de enseñanza son obligatorias.',
            'details.teachingcontent_practical_self_employment.array' => 'Las horas de autoempleo práctico del contenido de enseñanza deben ser un array.',
            'details.teachingcontent_practical_self_employment_duration.required' => 'Las duraciones de autoempleo práctico del contenido de enseñanza son obligatorias.',
            'details.teachingcontent_practical_self_employment_duration.array' => 'Las duraciones de autoempleo práctico del contenido de enseñanza deben ser un array.',
            'details.totalContactTeacherHours.required' => 'El total de horas de contacto con el profesor es obligatorio.',
            'details.totalContactTeacherHours.numeric' => 'El total de horas de contacto con el profesor debe ser un número.',
            'details.totalPracticalTeacherHours.required' => 'El total de horas de enseñanza práctica es obligatorio.',
            'details.totalPracticalTeacherHours.numeric' => 'El total de horas de enseñanza práctica debe ser un número.',
            'details.totalSelfEmploymentHours.required' => 'El total de horas de autoempleo es obligatorio.',
            'details.totalSelfEmploymentHours.numeric' => 'El total de horas de autoempleo debe ser un número.',
            'details.totalPracticalSelfEmploymentHours.required' => 'El total de horas de autoempleo práctico es obligatorio.',
            'details.totalPracticalSelfEmploymentHours.numeric' => 'El total de horas de autoempleo práctico debe ser un número.',
            'details.totalHours2.required' => 'El total de horas 2 es obligatorio.',
            'details.totalHours2.numeric' => 'El total de horas 2 debe ser un número.',
            'details.evaluation_unit.required' => 'Las unidades de evaluación son obligatorias.',
            'details.evaluation_unit.array' => 'Las unidades de evaluación deben ser un array.',
            'details.evaluation_Learning_outcomes.required' => 'Los resultados de aprendizaje de la evaluación son obligatorios.',
            'details.evaluation_Learning_outcomes.array' => 'Los resultados de aprendizaje de la evaluación deben ser un array.',
            'details.evaluation_type.required' => 'Los tipos de evaluación son obligatorios.',
            'details.evaluation_type.array' => 'Los tipos de evaluación deben ser un array.',
            'details.evaluation_criteria.required' => 'Los criterios de evaluación son obligatorios.',
            'details.evaluation_criteria.array' => 'Los criterios de evaluación deben ser un array.',
            'details.evaluation_activity.required' => 'Las actividades de evaluación son obligatorias.',
            'details.evaluation_activity.array' => 'Las actividades de evaluación deben ser un array.',
            'details.evaluation_first_partial.required' => 'Las evaluaciones del primer parcial son obligatorias.',
            'details.evaluation_first_partial.array' => 'Las evaluaciones del primer parcial deben ser un array.',
            'details.evaluation_second_partial.required' => 'Las evaluaciones del segundo parcial son obligatorias.',
            'details.evaluation_second_partial.array' => 'Las evaluaciones del segundo parcial deben ser un array.',
            'details.totalPartial1.required' => 'El total del primer parcial es obligatorio.',
            'details.totalPartial1.numeric' => 'El total del primer parcial debe ser un número.',
            'details.totalPartial2.required' => 'El total del segundo parcial es obligatorio.',
            'details.totalPartial2.numeric' => 'El total del segundo parcial debe ser un número.',
            'details.bibliography_type.required' => 'Los tipos de bibliografía son obligatorios.',
            'details.bibliography_type.array' => 'Los tipos de bibliografía deben ser un array.',
            'details.bibliography_author.required' => 'Los autores de la bibliografía son obligatorios.',
            'details.bibliography_author.array' => 'Los autores de la bibliografía deben ser un array.',
            'details.bibliography_year.required' => 'Los años de la bibliografía son obligatorios.',
            'details.bibliography_year.array' => 'Los años de la bibliografía deben ser un array.',
            'details.bibliography_title.required' => 'Los títulos de la bibliografía son obligatorios.',
            'details.bibliography_title.array' => 'Los títulos de la bibliografía deben ser un array.',
            'details.bibliography_editorial.required' => 'Las editoriales de la bibliografía son obligatorias.',
            'details.bibliography_editorial.array' => 'Las editoriales de la bibliografía deben ser un array.',
            'details.bibliography_format.required' => 'Los formatos de la bibliografía son obligatorios.',
            'details.bibliography_format.array' => 'Los formatos de la bibliografía deben ser un array.',
            'details.bibliography_code.required' => 'Los códigos de la bibliografía son obligatorios.',
            'details.bibliography_code.array' => 'Los códigos de la bibliografía deben ser un array.',
            'details.bibliography_link.required' => 'Los enlaces de la bibliografía son obligatorios.',
            'details.bibliography_link.array' => 'Los enlaces de la bibliografía deben ser un array.',
            'details.bibliography_uplift.required' => 'Los soportes de la bibliografía son obligatorios.',
            'details.bibliography_uplift.array' => 'Los soportes de la bibliografía deben ser un array.',
            'details.teacher_approval.required' => 'La aprobación del profesor es obligatoria.',
            'details.coordinator_approval.required' => 'La aprobación del coordinador es obligatoria.',
            'details.vice_rector_approval.required' => 'La aprobación del vicerrector es obligatoria.',
        ];
    }
}
